name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build & Pack
      run: dotnet build --configuration $env:Configuration

    - name: Test
      run: dotnet test --configuration $env:Configuration --no-build
